/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Board */
        post: operations["analyze_board_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /**
             * Now
             * Format: date-time
             */
            now: string;
            /** Columns */
            columns: components["schemas"]["ColumnIn"][];
            /** Cards */
            cards: components["schemas"]["CardIn"][];
            /** Events */
            events: components["schemas"]["EventIn"][];
            /**
             * Simulations
             * @default 10000
             */
            simulations?: number;
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            summary: components["schemas"]["Summary"];
            /** Throughput */
            throughput: components["schemas"]["WeekPoint"][];
            trend: components["schemas"]["Trend"] | null;
            forecast: components["schemas"]["Forecast"] | null;
            cycleTime: components["schemas"]["CycleTime"] | null;
            /** Stale */
            stale: components["schemas"]["StaleCard"][];
            /**
             * Insights
             * @description Conclusiones en lenguaje natural para mostrar en la UI
             */
            insights: string[];
            /** Warnings */
            warnings: string[];
        };
        /** CardIn */
        CardIn: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Columnid */
            columnId: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** CardPrediction */
        CardPrediction: {
            /** Cardid */
            cardId: string;
            /** Predictedleadtimedays */
            predictedLeadTimeDays: number;
            /** Elapseddays */
            elapsedDays: number;
            /** Remainingdays */
            remainingDays: number;
            /**
             * Overdue
             * @description Ya lleva más tiempo que lo predicho
             */
            overdue: boolean;
        };
        /** ColumnIn */
        ColumnIn: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Position
             * @description Clave de orden (fractional indexing). La menor es la primera columna.
             */
            position: string;
        };
        /** CycleTime */
        CycleTime: {
            /** Ntrain */
            nTrain: number;
            /**
             * Bestmodel
             * @enum {string}
             */
            bestModel: "baseline_median" | "linear_regression" | "gradient_boosting";
            /** Scores */
            scores: components["schemas"]["ModelScore"][];
            /**
             * Wipeffectdays
             * @description Días extra por cada tarjeta adicional en curso (coeficiente lineal)
             */
            wipEffectDays: number;
            /**
             * Kindeffectdays
             * @description Efecto de cada tipo de tarea vs. el promedio (lineal)
             */
            kindEffectDays: {
                [key: string]: number;
            };
            /** Predictions */
            predictions: components["schemas"]["CardPrediction"][];
        };
        /** EventIn */
        EventIn: {
            /** Cardid */
            cardId: string;
            /**
             * Type
             * @enum {string}
             */
            type: "created" | "moved" | "deleted";
            /** Fromcolumnid */
            fromColumnId?: string | null;
            /** Tocolumnid */
            toColumnId?: string | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** Forecast */
        Forecast: {
            /** Remaining */
            remaining: number;
            /** Simulations */
            simulations: number;
            /** Weeksofhistory */
            weeksOfHistory: number;
            p50: components["schemas"]["ForecastPoint"];
            p85: components["schemas"]["ForecastPoint"];
            p95: components["schemas"]["ForecastPoint"];
            /** Histogram */
            histogram: components["schemas"]["HistogramBin"][];
        };
        /** ForecastPoint */
        ForecastPoint: {
            /** Weeks */
            weeks: number;
            /**
             * Date
             * Format: date-time
             */
            date: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistogramBin */
        HistogramBin: {
            /** Weeks */
            weeks: number;
            /** Probability */
            probability: number;
        };
        /** ModelScore */
        ModelScore: {
            /**
             * Name
             * @enum {string}
             */
            name: "baseline_median" | "linear_regression" | "gradient_boosting";
            /**
             * Maedays
             * @description Error absoluto medio en validación cruzada (días)
             */
            maeDays: number;
        };
        /** StaleCard */
        StaleCard: {
            /** Cardid */
            cardId: string;
            /** Columnid */
            columnId: string;
            /** Daysincolumn */
            daysInColumn: number;
            /**
             * Typicaldays
             * @description Mediana histórica de permanencia en esa columna
             */
            typicalDays: number;
            /**
             * Thresholddays
             * @description Umbral IQR: Q3 + 1,5·IQR
             */
            thresholdDays: number;
        };
        /** Summary */
        Summary: {
            /** Cardstotal */
            cardsTotal: number;
            /**
             * Backlog
             * @description Tarjetas en la primera columna
             */
            backlog: number;
            /**
             * Inprogress
             * @description Tarjetas en columnas intermedias
             */
            inProgress: number;
            /**
             * Done
             * @description Tarjetas en la última columna
             */
            done: number;
            /** Donelast4Weeks */
            doneLast4Weeks: number;
            /** Leadtimemediandays */
            leadTimeMedianDays: number | null;
            /** Leadtimep85Days */
            leadTimeP85Days: number | null;
        };
        /** Trend */
        Trend: {
            /**
             * Slopeperweek
             * @description Cambio del throughput por semana (tarjetas/semana²)
             */
            slopePerWeek: number;
            /** Intercept */
            intercept: number;
            /** R2 */
            r2: number;
            /** Pvalue */
            pValue: number;
            /** Slopeci95 */
            slopeCi95: [
                number,
                number
            ];
            /**
             * Direction
             * @description 'flat' si la pendiente no es significativa (p ≥ 0,05)
             * @enum {string}
             */
            direction: "up" | "down" | "flat";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeekPoint */
        WeekPoint: {
            /**
             * Weekstart
             * Format: date-time
             */
            weekStart: string;
            /** Done */
            done: number;
            /**
             * Trend
             * @description Valor de la recta de regresión para esa semana
             */
            trend: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    analyze_board_analyze_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ml-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
